languages = [
    {"code": "abk", "name": "Abkhaz"},
    {"code": "ace", "name": "Acehnese"},
    {"code": "ach", "name": "Acholi"},
    {"code": "aar", "name": "Afar"},
    {"code": "af", "name": "Afrikaans"},
    {"code": "sq", "name": "Albanian"},
    {"code": "alz", "name": "Alur"},
    {"code": "am", "name": "Amharic"},
    {"code": "ar", "name": "Arabic"},
    {"code": "hy", "name": "Armenian"},
    {"code": "as", "name": "Assamese"},
    {"code": "ava", "name": "Avar"},
    {"code": "awa", "name": "Awadhi"},
    {"code": "ay", "name": "Aymara"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "ban", "name": "Balinese"},
    {"code": "bal", "name": "Baluchi"},
    {"code": "bm", "name": "Bambara"},
    {"code": "bci", "name": "Baoulé"},
    {"code": "bak", "name": "Bashkir"},
    {"code": "eu", "name": "Basque"},
    {"code": "btx", "name": "Batak Karo"},
    {"code": "bts", "name": "Batak Simalungun"},
    {"code": "bbc", "name": "Batak Toba"},
    {"code": "be", "name": "Belarusian"},
    {"code": "bem", "name": "Bemba"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bew", "name": "Betawi"},
    {"code": "bho", "name": "Bhojpuri"},
    {"code": "bik", "name": "Bikol"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "bre", "name": "Breton"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "bua", "name": "Buryat"},
    {"code": "yue", "name": "Cantonese"},
    {"code": "ca", "name": "Catalan"},
    {"code": "ceb", "name": "Cebuano"},
    {"code": "cha", "name": "Chamorro"},
    {"code": "che", "name": "Chechen"},
    {"code": "zh", "name": "Chinese"},
    {"code": "zh-cn", "name": "Chinese (Simplified)"},
    {"code": "zh-tw", "name": "Chinese (Traditional)"},
    {"code": "chk", "name": "Chuukese"},
    {"code": "chv", "name": "Chuvash"},
    {"code": "co", "name": "Corsican"},
    {"code": "crh", "name": "Crimean Tatar"},
    {"code": "hr", "name": "Croatian"},
    {"code": "cs", "name": "Czech"},
    {"code": "da", "name": "Danish"},
    {"code": "fa-af", "name": "Dari"},
    {"code": "dv", "name": "Dhivehi"},
    {"code": "din", "name": "Dinka"},
    {"code": "doi", "name": "Dogri"},
    {"code": "dom", "name": "Dombe"},
    {"code": "nl", "name": "Dutch"},
    {"code": "dyu", "name": "Dyula"},
    {"code": "dzo", "name": "Dzongkha"},
   
    {"code": "eo", "name": "Esperanto"},
    {"code": "et", "name": "Estonian"},
    {"code": "fao", "name": "Faroese"},
    {"code": "fij", "name": "Fijian"},
    {"code": "fil", "name": "Filipino (Tagalog)"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fon", "name": "Fon"},
    {"code": "fr", "name": "French"},
    {"code": "fy", "name": "Frisian"},
    {"code": "fur", "name": "Friulian"},
    {"code": "ful", "name": "Fulani"},
    {"code": "gaa", "name": "Ga"},
    {"code": "gl", "name": "Galician"},
    {"code": "ka", "name": "Georgian"},
    {"code": "de", "name": "German"},
    {"code": "el", "name": "Greek"},
    {"code": "gn", "name": "Guarani"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "ht", "name": "Haitian Creole"},
    {"code": "cnh", "name": "Hakha Chin"},
    {"code": "ha", "name": "Hausa"},
    {"code": "haw", "name": "Hawaiian"},
    {"code": "he", "name": "Hebrew"},
    {"code": "iw", "name": "Hebrew"},
    {"code": "hil", "name": "Hiligaynon"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hmn", "name": "Hmong"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "hrx", "name": "Hunsrik"},
    {"code": "iba", "name": "Iban"},
    {"code": "is", "name": "Icelandic"},
    {"code": "ig", "name": "Igbo"},
    {"code": "ilo", "name": "Ilocano"},
    {"code": "id", "name": "Indonesian"},
    {"code": "ga", "name": "Irish"},
    {"code": "it", "name": "Italian"},
    {"code": "jam", "name": "Jamaican Patois"},
    {"code": "ja", "name": "Japanese"},
    {"code": "jv", "name": "Javanese"},
    {"code": "jw", "name": "Javanese"},
    {"code": "kac", "name": "Jingpo"},
    {"code": "kal", "name": "Kalaallisut"},
    {"code": "kn", "name": "Kannada"},
    {"code": "kau", "name": "Kanuri"},
    {"code": "pam", "name": "Kapampangan"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "kha", "name": "Khasi"},
    {"code": "km", "name": "Khmer"},
    {"code": "cgg", "name": "Kiga"},
    {"code": "kik", "name": "Kikongo"},
    {"code": "rw", "name": "Kinyarwanda"},
    {"code": "ktu", "name": "Kituba"},
    {"code": "trp", "name": "Kokborok"},
    {"code": "kom", "name": "Komi"},
    {"code": "gom", "name": "Konkani"},
    {"code": "ko", "name": "Korean"},
    {"code": "kri", "name": "Krio"},
    {"code": "ku", "name": "Kurdish"},
    {"code": "ckb", "name": "Kurdish (Sorani)"},
    {"code": "ky", "name": "Kyrgyz"},
    {"code": "lo", "name": "Lao"},
    {"code": "ltg", "name": "Latgalian"},
    {"code": "la", "name": "Latin"},
    {"code": "lv", "name": "Latvian"},
    {"code": "lij", "name": "Ligurian"},
    {"code": "lim", "name": "Limburgish"},
    {"code": "ln", "name": "Lingala"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "lmo", "name": "Lombard"},
    {"code": "lg", "name": "Luganda"},
    {"code": "luo", "name": "Luo"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "mad", "name": "Madurese"},
    {"code": "mai", "name": "Maithili"},
    {"code": "mak", "name": "Makassar"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "ms", "name": "Malay"},
    {"code": "ms-arab", "name": "Malay (Jawi)"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "mt", "name": "Maltese"},
    {"code": "mam", "name": "Mam"},
    {"code": "glv", "name": "Manx"},
    {"code": "mi", "name": "Maori"},
    {"code": "mr", "name": "Marathi"},
    {"code": "mah", "name": "Marshallese"},
    {"code": "mwr", "name": "Marwadi"},
    {"code": "mfe", "name": "Mauritian Creole"},
    {"code": "mhr", "name": "Meadow Mari"},
    {"code": "mni-mtei", "name": "Meiteilon (Manipuri)"},
    {"code": "min", "name": "Minang"},
    {"code": "lus", "name": "Mizo"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "my", "name": "Myanmar (Burmese)"},
    {"code": "nhe", "name": "Nahuatl (Eastern Huasteca)"},
    {"code": "ndc-zw", "name": "Ndau"},
    {"code": "nde", "name": "Ndebele (South)"},
    {"code": "new", "name": "Nepalbhasa (Newari)"},
    {"code": "ne", "name": "Nepali"},
    {"code": "no", "name": "Norwegian"},
    {"code": "nus", "name": "Nuer"},
    {"code": "ny", "name": "Nyanja (Chichewa)"},
    {"code": "oci", "name": "Occitan"},
    {"code": "or", "name": "Odia (Oriya)"},
    {"code": "om", "name": "Oromo"},
    {"code": "oss", "name": "Ossetian"},
    {"code": "pag", "name": "Pangasinan"},
    {"code": "pap", "name": "Papiamento"},
    {"code": "ps", "name": "Pashto"},
    {"code": "fa", "name": "Persian"},
    {"code": "pl", "name": "Polish"},
    {"code": "por", "name": "Portuguese (Portugal)"},
    {"code": "pt", "name": "Portuguese (Portugal, Brazil)"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "pa-arab", "name": "Punjabi (Shahmukhi)"},
    {"code": "kek", "name": "Q'eqchi'"},
    {"code": "qu", "name": "Quechua"},
    {"code": "rom", "name": "Romani"},
    {"code": "ro", "name": "Romanian"},
    {"code": "run", "name": "Rundi"},
    {"code": "ru", "name": "Russian"},
    {"code": "sme", "name": "Sami (North)"},
    {"code": "sm", "name": "Samoan"},
    {"code": "sag", "name": "Sango"},
    {"code": "sa", "name": "Sanskrit"},
    {"code": "sat", "name": "Santali"},
    {"code": "gd", "name": "Scots Gaelic"},
    {"code": "nso", "name": "Sepedi"},
    {"code": "sr", "name": "Serbian"},
    {"code": "st", "name": "Sesotho"},
    {"code": "crs", "name": "Seychellois Creole"},
    {"code": "shn", "name": "Shan"},
    {"code": "sn", "name": "Shona"},
    {"code": "scn", "name": "Sicilian"},
    {"code": "szl", "name": "Silesian"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "si", "name": "Sinhala (Sinhalese)"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "so", "name": "Somali"},
    {"code": "es", "name": "Spanish"},
    {"code": "su", "name": "Sundanese"},
    {"code": "sus", "name": "Susu"},
    {"code": "sw", "name": "Swahili"},
    {"code": "ssw", "name": "Swati"},
    {"code": "sv", "name": "Swedish"},
    {"code": "tl", "name": "Tagalog (Filipino)"},
    {"code": "tah", "name": "Tahitian"},
    {"code": "tg", "name": "Tajik"},
    {"code": "ber-atn", "name": "Tamazight"},
    {"code": "ber", "name": "Tamazight (Tifinagh)"},
    {"code": "ta", "name": "Tamil"},
    {"code": "tt", "name": "Tatar"},
    {"code": "te", "name": "Telugu"},
    {"code": "tet", "name": "Tetum"},
    {"code": "th", "name": "Thai"},
    {"code": "bod", "name": "Tibetan"},
    {"code": "ti", "name": "Tigrinya"},
    {"code": "tiv", "name": "Tiv"},
    {"code": "tpi", "name": "Tok Pisin"},
    {"code": "ton", "name": "Tongan"},
    {"code": "ts", "name": "Tsonga"},
    {"code": "tsn", "name": "Tswana"},
    {"code": "tcy", "name": "Tulu"},
    {"code": "tum", "name": "Tumbuka"},
    {"code": "tr", "name": "Turkish"},
    {"code": "tk", "name": "Turkmen"},
    {"code": "tuk", "name": "Tuvan"},
    {"code": "ak", "name": "Twi (Akan)"},
    {"code": "udm", "name": "Udmurt"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "ug", "name": "Uyghur"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "ven", "name": "Venda"},
    {"code": "vec", "name": "Venetian"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "war", "name": "Waray"},
    {"code": "cy", "name": "Welsh"},
    {"code": "wol", "name": "Wolof"},
    {"code": "xh", "name": "Xhosa"},
    {"code": "sah", "name": "Yakut"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "yo", "name": "Yoruba"},
    {"code": "yua", "name": "Yucatec Maya"},
    {"code": "zap", "name": "Zapotec"},
    {"code": "zu", "name": "Zulu"},
]
